version: '3.8'

services:
    ***REMOVED***:
        container_name: ***REMOVED***_***REMOVED***
        image: ***REMOVED***
        ports:
            - 5432:5432

        env_file:
            - .env
        volumes:
            - ***REMOVED***_data:/var/lib/***REMOVED***ql/data

    app:
        container_name: banco_horas_app
        build: .
        ports:
            - 8080:8080
        env_file:
            - .env
        depends_on:
            - ***REMOVED***
        restart: always

volumes:
    ***REMOVED***_data: