version: '3.8'

services:
    ***REMOVED***:
        container_name: ***REMOVED***_***REMOVED***
        image: ***REMOVED***
        ports:
            - 5432:5432

        environment:
            - POSTGRES_USER=***REMOVED***
            - POSTGRES_PASSWORD=***REMOVED***
            - POSTGRES_DB=***REMOVED***
        volumes:
            - ***REMOVED***_data:/var/lib/***REMOVED***ql/data

volumes:
    ***REMOVED***_data: