spring:
    application:
        name: banco_de_horas

    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
        encoding: UTF-8
        cache: false
        check-template: true
        check-template-location: true
        servlet:
            content-type: text/html

    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
        livereload:
            enabled: true
            port: 35729
        remote:
            restart:
                enabled: true

    web:
        resources:
            static-locations: classpath:/static/
            cache:
                period: 0

    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

app:
    base-url: ${APP_BASE_URL}

server:
    port: 8080